// SPDX-License-Identifier: MIT

import XCTest
@testable import AetherNetProtocol

/// Cross-language DTN-envelope parity: the Swift port must reproduce the Go
/// oracle's byte vectors (`fixtures/dtn/expected/<name>.bin`, generated by
/// `go/cmd/dtnfixturegen`) byte-for-byte for every case in
/// `fixtures/dtn/inputs.json`, then deserialize each back to matching fields.
/// Any drift between Swift and the other seven ports surfaces here as a byte
/// mismatch. See `fixtures/README.md`.
final class DtnEnvelopeFixtureTests: XCTestCase {

    private func fixturesDir() -> URL {
        var url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        for _ in 0..<10 {
            let candidate = url.appendingPathComponent("fixtures/dtn/inputs.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                return url.appendingPathComponent("fixtures/dtn")
            }
            url = url.deletingLastPathComponent()
        }
        XCTFail("Could not locate fixtures/dtn/inputs.json")
        return URL(fileURLWithPath: "fixtures/dtn")
    }

    private struct Input: Decodable {
        let kind: String
        let name: String
        let id: String?
        let priority: Int?
        let status: Int?
        let copy_count: Int?
        let max_copies: Int?
        let hop_count: Int?
        let created_at_ms: Int64?
        let expires_at_ms: Int64?
        let sender_uhid: String?
        let recipient_uhid: String?
        let sender_geohash: String?
        let recipient_last_geohash: String?
        let encrypted_payload_hex: String?
        let encrypted_payload_len: Int?
        let bundle_id: String?
        let accepted: Bool?
        let total_hops: Int32?
        let total_custody_transfers: Int32?
        let delivered_at_ms: Int64?
    }

    private func loadInputs() throws -> [Input] {
        let url = fixturesDir().appendingPathComponent("inputs.json")
        return try JSONDecoder().decode([Input].self, from: Data(contentsOf: url))
    }

    private func expectedBytes(_ name: String) throws -> Data {
        try Data(contentsOf: fixturesDir().appendingPathComponent("expected/\(name).bin"))
    }

    private func hexToData(_ hex: String) -> Data {
        var data = Data()
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            data.append(UInt8(hex[idx..<next], radix: 16)!)
            idx = next
        }
        return data
    }

    private func payloadFor(_ inp: Input) -> Data {
        if let len = inp.encrypted_payload_len, len > 0 {
            return Data((0..<len).map { UInt8($0 % 256) })
        }
        return hexToData(inp.encrypted_payload_hex ?? "")
    }

    private func serialize(_ inp: Input) -> Data {
        switch inp.kind {
        case "bundle":
            let b = DtnBundle(
                id: UUID(uuidString: inp.id!)!,
                senderUhid: inp.sender_uhid ?? "",
                recipientUhid: inp.recipient_uhid ?? "",
                encryptedPayload: payloadFor(inp),
                priority: Int32(inp.priority ?? 0),
                status: Int32(inp.status ?? 0),
                copyCount: Int32(inp.copy_count ?? 0),
                maxCopies: Int32(inp.max_copies ?? 0),
                senderGeohash: inp.sender_geohash,
                recipientLastGeohash: inp.recipient_last_geohash,
                hopCount: Int32(inp.hop_count ?? 0),
                createdAt: Date(timeIntervalSince1970: Double(inp.created_at_ms ?? 0) / 1000),
                expiresAt: Date(timeIntervalSince1970: Double(inp.expires_at_ms ?? 0) / 1000)
            )
            return DtnEnvelope.serializeBundle(b)
        case "custody_ack":
            return DtnEnvelope.serializeCustodyAck(
                bundleId: UUID(uuidString: inp.bundle_id!)!,
                accepted: inp.accepted ?? false)
        case "delivery_receipt":
            let r = DtnDeliveryReceipt(
                bundleId: UUID(uuidString: inp.bundle_id!)!,
                recipientUhid: inp.recipient_uhid ?? "",
                totalHops: inp.total_hops ?? 0,
                totalCustodyTransfers: inp.total_custody_transfers ?? 0,
                deliveredAt: Date(timeIntervalSince1970: Double(inp.delivered_at_ms ?? 0) / 1000)
            )
            return DtnEnvelope.serializeDeliveryReceipt(r)
        default:
            XCTFail("unknown kind \(inp.kind)")
            return Data()
        }
    }

    func test_serializeMatchesGoOracle() throws {
        for inp in try loadInputs() {
            XCTAssertEqual(serialize(inp), try expectedBytes(inp.name),
                           "\(inp.name): serialize byte mismatch — see fixtures/README.md")
        }
    }

    func test_deserializeRoundTrip() throws {
        for inp in try loadInputs() {
            let data = try expectedBytes(inp.name)
            switch inp.kind {
            case "bundle":
                guard let b = DtnEnvelope.deserializeBundle(data) else {
                    XCTFail("\(inp.name): deserializeBundle returned nil"); continue
                }
                XCTAssertEqual(b.id, UUID(uuidString: inp.id!)!, "\(inp.name) id")
                XCTAssertEqual(Int(b.priority), inp.priority ?? 0, "\(inp.name) priority")
                XCTAssertEqual(Int(b.status), inp.status ?? 0, "\(inp.name) status")
                XCTAssertEqual(Int(b.copyCount), inp.copy_count ?? 0, "\(inp.name) copy_count")
                XCTAssertEqual(Int(b.maxCopies), inp.max_copies ?? 0, "\(inp.name) max_copies")
                XCTAssertEqual(Int(b.hopCount), inp.hop_count ?? 0, "\(inp.name) hop_count")
                XCTAssertEqual(Int64(b.createdAt.timeIntervalSince1970 * 1000), inp.created_at_ms ?? 0, "\(inp.name) created_at")
                XCTAssertEqual(Int64(b.expiresAt.timeIntervalSince1970 * 1000), inp.expires_at_ms ?? 0, "\(inp.name) expires_at")
                XCTAssertEqual(b.senderUhid, inp.sender_uhid ?? "", "\(inp.name) sender_uhid")
                XCTAssertEqual(b.recipientUhid, inp.recipient_uhid ?? "", "\(inp.name) recipient_uhid")
                XCTAssertEqual(b.senderGeohash ?? "", inp.sender_geohash ?? "", "\(inp.name) sender_geohash")
                XCTAssertEqual(b.recipientLastGeohash ?? "", inp.recipient_last_geohash ?? "", "\(inp.name) recipient_last_geohash")
                XCTAssertEqual(b.encryptedPayload, payloadFor(inp), "\(inp.name) payload")
            case "custody_ack":
                guard let (id, accepted) = DtnEnvelope.deserializeCustodyAck(data) else {
                    XCTFail("\(inp.name): deserializeCustodyAck returned nil"); continue
                }
                XCTAssertEqual(id, UUID(uuidString: inp.bundle_id!)!, "\(inp.name) bundle_id")
                XCTAssertEqual(accepted, inp.accepted ?? false, "\(inp.name) accepted")
            case "delivery_receipt":
                guard let r = DtnEnvelope.deserializeDeliveryReceipt(data) else {
                    XCTFail("\(inp.name): deserializeDeliveryReceipt returned nil"); continue
                }
                XCTAssertEqual(r.bundleId, UUID(uuidString: inp.bundle_id!)!, "\(inp.name) bundle_id")
                XCTAssertEqual(r.recipientUhid, inp.recipient_uhid ?? "", "\(inp.name) recipient_uhid")
                XCTAssertEqual(r.totalHops, inp.total_hops ?? 0, "\(inp.name) total_hops")
                XCTAssertEqual(r.totalCustodyTransfers, inp.total_custody_transfers ?? 0, "\(inp.name) total_custody_transfers")
                XCTAssertEqual(Int64(r.deliveredAt.timeIntervalSince1970 * 1000), inp.delivered_at_ms ?? 0, "\(inp.name) delivered_at")
            default:
                XCTFail("unknown kind \(inp.kind)")
            }
        }
    }
}
