// SPDX-License-Identifier: MIT

import XCTest
@testable import AetherNetProtocol

/// Cross-language circuit-relay-v2 parity: the Swift port must reproduce the Go
/// oracle's byte vectors (`fixtures/circuit-relay/expected/<name>.bin`, generated by
/// `go/cmd/circuitrelayfixturegen`) byte-for-byte for every case in
/// `fixtures/circuit-relay/inputs.json`, then deserialize each back to matching fields.
final class RelayFrameFixtureTests: XCTestCase {

    private func fixturesDir() -> URL {
        var url = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        for _ in 0..<10 {
            let candidate = url.appendingPathComponent("fixtures/circuit-relay/inputs.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                return url.appendingPathComponent("fixtures/circuit-relay")
            }
            url = url.deletingLastPathComponent()
        }
        XCTFail("Could not locate fixtures/circuit-relay/inputs.json")
        return URL(fileURLWithPath: "fixtures/circuit-relay")
    }

    private struct Input: Decodable {
        let name: String
        let type: Int
        let status: Int?
        let source_uhid: String?
        let destination_uhid: String?
        let relay_uhid: String?
        let connection_id: String?
        let reservation_expires_at_ms: Int64?
        let limit_duration_seconds: Int32?
        let limit_data_bytes: Int64?
        let payload_hex: String?
        let payload_len: Int?
    }

    private func loadInputs() throws -> [Input] {
        let url = fixturesDir().appendingPathComponent("inputs.json")
        return try JSONDecoder().decode([Input].self, from: Data(contentsOf: url))
    }

    private func expectedBytes(_ name: String) throws -> Data {
        try Data(contentsOf: fixturesDir().appendingPathComponent("expected/\(name).bin"))
    }

    private func hexToData(_ hex: String) -> Data {
        var data = Data()
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            data.append(UInt8(hex[idx..<next], radix: 16)!)
            idx = next
        }
        return data
    }

    private func payloadFor(_ inp: Input) -> Data {
        if let len = inp.payload_len, len > 0 {
            return Data((0..<len).map { UInt8($0 % 256) })
        }
        return hexToData(inp.payload_hex ?? "")
    }

    private func connId(_ s: String?) -> UUID {
        if let s = s, !s.isEmpty { return UUID(uuidString: s)! }
        return UUID(uuid: (0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
    }

    private func toFrame(_ inp: Input) -> RelayFrame {
        RelayFrame(
            type: RelayMessageType(rawValue: UInt8(inp.type))!,
            status: RelayStatus(rawValue: UInt8(inp.status ?? 0))!,
            sourceUhid: inp.source_uhid ?? "",
            destinationUhid: inp.destination_uhid ?? "",
            relayUhid: inp.relay_uhid ?? "",
            connectionId: connId(inp.connection_id),
            reservationExpiresAtMs: inp.reservation_expires_at_ms ?? 0,
            limitDurationSeconds: inp.limit_duration_seconds ?? 0,
            limitDataBytes: inp.limit_data_bytes ?? 0,
            payload: payloadFor(inp))
    }

    func test_serializeMatchesGoOracle() throws {
        for inp in try loadInputs() {
            XCTAssertEqual(RelayFrameSerializer.serialize(toFrame(inp)), try expectedBytes(inp.name),
                           "\(inp.name): serialize byte mismatch — see fixtures/README.md")
        }
    }

    func test_deserializeRoundTrip() throws {
        for inp in try loadInputs() {
            let data = try expectedBytes(inp.name)
            guard let f = RelayFrameSerializer.deserialize(data) else {
                XCTFail("\(inp.name): deserialize returned nil"); continue
            }
            XCTAssertEqual(f.type.rawValue, UInt8(inp.type), "\(inp.name) type")
            XCTAssertEqual(f.status.rawValue, UInt8(inp.status ?? 0), "\(inp.name) status")
            XCTAssertEqual(f.sourceUhid, inp.source_uhid ?? "", "\(inp.name) source_uhid")
            XCTAssertEqual(f.destinationUhid, inp.destination_uhid ?? "", "\(inp.name) destination_uhid")
            XCTAssertEqual(f.relayUhid, inp.relay_uhid ?? "", "\(inp.name) relay_uhid")
            XCTAssertEqual(f.connectionId, connId(inp.connection_id), "\(inp.name) connection_id")
            XCTAssertEqual(f.reservationExpiresAtMs, inp.reservation_expires_at_ms ?? 0, "\(inp.name) reservation_expires_at_ms")
            XCTAssertEqual(f.limitDurationSeconds, inp.limit_duration_seconds ?? 0, "\(inp.name) limit_duration_seconds")
            XCTAssertEqual(f.limitDataBytes, inp.limit_data_bytes ?? 0, "\(inp.name) limit_data_bytes")
            XCTAssertEqual(f.payload, payloadFor(inp), "\(inp.name) payload")
        }
    }
}
