// SPDX-License-Identifier: MIT
// Cross-language DTN-envelope parity: the C port must reproduce the Go oracle's
// byte vectors (fixtures/dtn/expected/<name>.bin, generated by go/cmd/dtnfixturegen)
// byte-for-byte for every case in fixtures/dtn/inputs.json, then deserialize each
// back to matching fields. Any drift between C and the other seven ports surfaces
// here as a byte mismatch. The cases are transcribed in C (no JSON parser on the
// test surface, mirroring test_bandwidth_fixtures.c / test_p256.c). Run from the
// repo root so the relative fixture paths resolve. See fixtures/README.md.

#define _POSIX_C_SOURCE 200809L

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aethernet/dtn.h"
#include "aethernet/dtn_envelope.h"
#include "aethernet/protocol.h"

// All bundle fixtures share these whole-second-aligned timestamps.
#define CREATED_MS 1710528000000LL
#define EXPIRES_MS 1710787200000LL

static int tests_run = 0;

#define FAILF(name, ...) do { \
    fprintf(stderr, "FAIL [%s]: ", (name)); fprintf(stderr, __VA_ARGS__); fprintf(stderr, "\n"); \
    exit(1); \
} while (0)

static int hexv(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

// Parse a dashed/undashed UUID string into 16 RFC-4122 big-endian bytes.
static bool parse_uuid_str(const char *s, uint8_t out[16]) {
    int n = 0;
    while (*s && n < 16) {
        if (*s == '-') { s++; continue; }
        int hi = hexv(s[0]);
        if (hi < 0 || s[1] == '\0') return false;
        int lo = hexv(s[1]);
        if (lo < 0) return false;
        out[n++] = (uint8_t)((hi << 4) | lo);
        s += 2;
    }
    return n == 16;
}

// Hex string → fresh byte buffer (NULL for an empty string; *out_len set either way).
static uint8_t *hex_to_bytes(const char *hex, uint32_t *out_len) {
    size_t hl = strlen(hex);
    uint32_t n = (uint32_t)(hl / 2);
    *out_len = n;
    if (n == 0) return NULL;
    uint8_t *b = (uint8_t *)malloc(n);
    for (uint32_t i = 0; i < n; i++) {
        b[i] = (uint8_t)((hexv(hex[i * 2]) << 4) | hexv(hex[i * 2 + 1]));
    }
    return b;
}

static bool streq_or_empty(const char *a, const char *b) {
    return strcmp(a ? a : "", b ? b : "") == 0;
}

static uint8_t *read_expected(const char *name, long *out_len) {
    char path[256];
    snprintf(path, sizeof path, "fixtures/dtn/expected/%s.bin", name);
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (len < 0) { fclose(f); return NULL; }
    uint8_t *buf = (uint8_t *)malloc((size_t)(len > 0 ? len : 1));
    if (!buf) { fclose(f); return NULL; }
    size_t got = fread(buf, 1, (size_t)len, f);
    fclose(f);
    if ((long)got != len) { free(buf); return NULL; }
    *out_len = len;
    return buf;
}

// Serialize a bundle, assert byte-identity with the oracle vector, then decode the
// vector back and assert every field round-trips. `payload` is borrowed.
static void check_bundle(const char *name, const char *uuid,
                         uint8_t priority, uint8_t status,
                         int32_t copy_count, int32_t max_copies, int32_t hop_count,
                         const char *sender_uhid, const char *recipient_uhid,
                         const char *sender_geohash, const char *recipient_last_geohash,
                         const uint8_t *payload, uint32_t payload_len) {
    aethernet_dtn_bundle_t b;
    memset(&b, 0, sizeof b);
    if (!parse_uuid_str(uuid, b.id)) FAILF(name, "bad uuid");
    b.priority = priority;
    b.status = status;
    b.copy_count = copy_count;
    b.max_copies = max_copies;
    b.hop_count = hop_count;
    b.created_at_ms = CREATED_MS;
    b.expires_at_ms = EXPIRES_MS;
    b.sender_uhid = (char *)sender_uhid;
    b.recipient_uhid = (char *)recipient_uhid;
    b.sender_geohash = (char *)sender_geohash;
    b.recipient_last_geohash = (char *)recipient_last_geohash;
    b.encrypted_payload = (uint8_t *)payload;
    b.encrypted_payload_len = payload_len;

    uint8_t *enc = NULL;
    uint32_t enc_len = 0;
    if (!aethernet_dtn_bundle_encode(&b, &enc, &enc_len)) FAILF(name, "encode failed");

    long exp_len = 0;
    uint8_t *exp = read_expected(name, &exp_len);
    if (!exp) FAILF(name, "missing fixtures/dtn/expected/%s.bin (run from repo root)", name);
    if ((long)enc_len != exp_len || memcmp(enc, exp, enc_len) != 0) {
        FAILF(name, "serialize byte mismatch (got %u bytes, expected %ld)", enc_len, exp_len);
    }
    free(enc);

    aethernet_dtn_bundle_t *d = aethernet_dtn_bundle_decode(exp, (uint32_t)exp_len);
    if (!d) FAILF(name, "decode returned NULL");
    if (memcmp(d->id, b.id, AETHERNET_PACKET_ID_SIZE) != 0) FAILF(name, "id");
    if (d->priority != priority) FAILF(name, "priority");
    if (d->status != status) FAILF(name, "status");
    if (d->copy_count != copy_count) FAILF(name, "copy_count");
    if (d->max_copies != max_copies) FAILF(name, "max_copies");
    if (d->hop_count != hop_count) FAILF(name, "hop_count");
    if (d->created_at_ms != CREATED_MS) FAILF(name, "created_at_ms");
    if (d->expires_at_ms != EXPIRES_MS) FAILF(name, "expires_at_ms");
    if (!streq_or_empty(d->sender_uhid, sender_uhid)) FAILF(name, "sender_uhid");
    if (!streq_or_empty(d->recipient_uhid, recipient_uhid)) FAILF(name, "recipient_uhid");
    if (!streq_or_empty(d->sender_geohash, sender_geohash)) FAILF(name, "sender_geohash");
    if (!streq_or_empty(d->recipient_last_geohash, recipient_last_geohash)) FAILF(name, "recipient_last_geohash");
    if (d->encrypted_payload_len != payload_len) FAILF(name, "payload_len");
    if (payload_len && memcmp(d->encrypted_payload, payload, payload_len) != 0) FAILF(name, "payload bytes");
    aethernet_dtn_bundle_free(d);
    free(exp);

    printf("  %s OK\n", name);
    tests_run++;
}

static void check_custody_ack(const char *name, const char *uuid, bool accepted) {
    uint8_t id[AETHERNET_PACKET_ID_SIZE];
    if (!parse_uuid_str(uuid, id)) FAILF(name, "bad uuid");

    uint8_t *enc = NULL;
    uint32_t enc_len = 0;
    if (!aethernet_dtn_custody_ack_encode(id, accepted, &enc, &enc_len)) FAILF(name, "encode failed");

    long exp_len = 0;
    uint8_t *exp = read_expected(name, &exp_len);
    if (!exp) FAILF(name, "missing fixture");
    if ((long)enc_len != exp_len || memcmp(enc, exp, enc_len) != 0) {
        FAILF(name, "serialize byte mismatch (got %u, expected %ld)", enc_len, exp_len);
    }
    free(enc);

    uint8_t dec_id[AETHERNET_PACKET_ID_SIZE];
    bool dec_accepted = !accepted;
    if (!aethernet_dtn_custody_ack_decode(exp, (uint32_t)exp_len, dec_id, &dec_accepted)) FAILF(name, "decode failed");
    if (memcmp(dec_id, id, AETHERNET_PACKET_ID_SIZE) != 0) FAILF(name, "bundle_id");
    if (dec_accepted != accepted) FAILF(name, "accepted");
    free(exp);

    printf("  %s OK\n", name);
    tests_run++;
}

static void check_delivery_receipt(const char *name, const char *uuid, const char *recipient_uhid,
                                   int32_t total_hops, int32_t total_custody_transfers,
                                   int64_t delivered_at_ms) {
    uint8_t id[AETHERNET_PACKET_ID_SIZE];
    if (!parse_uuid_str(uuid, id)) FAILF(name, "bad uuid");

    uint8_t *enc = NULL;
    uint32_t enc_len = 0;
    if (!aethernet_dtn_delivery_receipt_encode(id, recipient_uhid, total_hops, total_custody_transfers,
                                               delivered_at_ms, &enc, &enc_len)) {
        FAILF(name, "encode failed");
    }

    long exp_len = 0;
    uint8_t *exp = read_expected(name, &exp_len);
    if (!exp) FAILF(name, "missing fixture");
    if ((long)enc_len != exp_len || memcmp(enc, exp, enc_len) != 0) {
        FAILF(name, "serialize byte mismatch (got %u, expected %ld)", enc_len, exp_len);
    }
    free(enc);

    uint8_t dec_id[AETHERNET_PACKET_ID_SIZE];
    char *dec_recipient = NULL;
    int32_t dec_hops = 0, dec_transfers = 0;
    int64_t dec_delivered = 0;
    if (!aethernet_dtn_delivery_receipt_decode(exp, (uint32_t)exp_len, dec_id, &dec_recipient,
                                               &dec_hops, &dec_transfers, &dec_delivered)) {
        FAILF(name, "decode failed");
    }
    if (memcmp(dec_id, id, AETHERNET_PACKET_ID_SIZE) != 0) FAILF(name, "bundle_id");
    if (!streq_or_empty(dec_recipient, recipient_uhid)) FAILF(name, "recipient_uhid");
    if (dec_hops != total_hops) FAILF(name, "total_hops");
    if (dec_transfers != total_custody_transfers) FAILF(name, "total_custody_transfers");
    if (dec_delivered != delivered_at_ms) FAILF(name, "delivered_at_ms");
    free(dec_recipient);
    free(exp);

    printf("  %s OK\n", name);
    tests_run++;
}

int main(void) {
    printf("Aether DTN Envelope — Cross-Language Fixture Parity\n");
    printf("===================================================\n");

    uint32_t plen = 0;
    uint8_t *p;

    p = hex_to_bytes("deadbeefcafe", &plen);
    check_bundle("dtn_bundle_basic", "11111111-2222-3333-4444-555555555555",
                 1, 1, 1, 3, 2, "carrier-1", "recipient-1", "u4pruyd", "u4pruye", p, plen);
    free(p);

    check_bundle("dtn_bundle_empty_payload", "22222222-3333-4444-5555-666666666666",
                 0, 0, 1, 3, 0, "carrier-1", "recipient-1", "u4pruyd", "u4pruye", NULL, 0);

    p = hex_to_bytes("00", &plen);
    check_bundle("dtn_bundle_empty_geohash", "33333333-4444-5555-6666-777777777777",
                 1, 1, 1, 3, 1, "carrier-1", "recipient-1", "", "", p, plen);
    free(p);

    // Multibyte UTF-8 UHIDs (Korean sender, Russian recipient) — UTF-8 source
    // literals, the same bytes the Go oracle emitted.
    p = hex_to_bytes("0102030405", &plen);
    check_bundle("dtn_bundle_unicode_uhids", "44444444-5555-6666-7777-888888888888",
                 2, 1, 2, 3, 1, "송신자-노드", "получатель-узел", "wydm", "ucfv", p, plen);
    free(p);

    // 65537-byte payload, byte[i] = i % 256 — proves the int32 length prefix.
    uint8_t *large = (uint8_t *)malloc(65537);
    for (uint32_t i = 0; i < 65537; i++) large[i] = (uint8_t)(i % 256);
    check_bundle("dtn_bundle_large_payload", "55555555-6666-7777-8888-999999999999",
                 1, 1, 1, 3, 0, "carrier-1", "recipient-1", "u4pruyd", "u4pruye", large, 65537);
    free(large);

    p = hex_to_bytes("ff", &plen);
    check_bundle("dtn_bundle_sos", "66666666-7777-8888-9999-aaaaaaaaaaaa",
                 3, 0, 1, 3, 0, "carrier-1", "recipient-1", "u4pruyd", "u4pruye", p, plen);
    free(p);

    p = hex_to_bytes("abcd", &plen);
    check_bundle("dtn_bundle_high_hops", "77777777-8888-9999-aaaa-bbbbbbbbbbbb",
                 1, 1, 300, 1000, 300, "carrier-1", "recipient-1", "u4pruyd", "u4pruye", p, plen);
    free(p);

    check_custody_ack("dtn_custody_ack_accepted", "11111111-2222-3333-4444-555555555555", true);
    check_custody_ack("dtn_custody_ack_refused", "11111111-2222-3333-4444-555555555555", false);

    check_delivery_receipt("dtn_delivery_receipt_basic", "11111111-2222-3333-4444-555555555555",
                           "recipient-1", 5, 3, 1710700000000LL);

    printf("\n%d fixture cases passed.\n", tests_run);
    return 0;
}
