"""Protocol constants for the Aether mesh networking protocol."""

# Routing constants
DEFAULT_TTL = 7
SOS_TTL = 15
ROUTE_TIMEOUT_MS = 5000
ROUTE_EXPIRY_SECONDS = 300

# BLE Discovery constants
BLE_DISCOVERY_INTERVAL_MS = 10000
BLE_SCAN_ON_MS = 2000
BLE_SCAN_OFF_MS = 8000
BLE_ADVERTISE_INTERVAL_MS = 1000
BLE_UUID_ROTATION_SECONDS = 900
BLE_SCAN_JITTER_MAX_MS = 2000
AETHER_BLE_SERVICE_UUID = "A3E71001-0001-0000-000000000000"

# Security constants
PACKET_NONCE_SIZE = 8
MAX_PACKET_AGE_SECONDS = 300
PROTOCOL_VERSION_UNSIGNED = 1
PROTOCOL_VERSION_SIGNED = 2
MAX_SKIPPED_KEYS = 1000
AES_GCM_NONCE_SIZE = 12
AES_GCM_TAG_SIZE = 16

# SOS constants
# SOS_PRIORITY: byte value used in MeshPacket.priority for emergency packets.
# Was originally 999 — invalid for a single byte; corrected to 255 to match the
# C# reference (ProtocolConstants.SosPriority).
SOS_PRIORITY = 255
MAX_SOS_BROADCASTS_PER_HOUR = 3

# DTN constants
DTN_BUNDLE_TTL_HOURS = 72
DTN_MAX_COPIES = 3
DTN_MAX_BUNDLES_PER_NODE = 50
DTN_SCAN_INTERVAL_SECONDS = 60

# Transport constants
BLE_MAX_PAYLOAD_BYTES = 1024
DEFAULT_CHUNK_SIZE_BYTES = 262144
MAX_CHUNK_SIZE_BYTES = 1048576
WIFI_DIRECT_TIMEOUT_MS = 10000
MAX_WIFI_DIRECT_PEERS = 8

# Heartbeat constants
HEARTBEAT_INTERVAL_SECONDS = 300
NODE_OFFLINE_THRESHOLD_SECONDS = 900

# Presence constants
PRESENCE_BEACON_INTERVAL_MS = 15000
PRESENCE_TIMEOUT_SECONDS = 60
EPHEMERAL_ID_ROTATION_MINUTES = 15
PROXIMITY_EVENT_DEBOUNCE_SECONDS = 30

# Voice constants
VOICE_FRAME_DURATION_MS = 20
PTT_MAX_DURATION_SECONDS = 60
JITTER_BUFFER_MIN_MS = 20
JITTER_BUFFER_MAX_MS = 200
OPUS_DEFAULT_BITRATE_KBPS = 64
MAX_GROUP_VOICE_MEMBERS = 8

# Streaming constants
DEFAULT_SEGMENT_DURATION_MS = 3000
MAX_STREAM_TREE_FANOUT = 4
MAX_STREAM_RELAY_HOPS = 3
STREAM_SEGMENT_BUFFER_SIZE = 10
BLE_AUDIO_BITRATE_KBPS = 64
WIFI_DIRECT_VIDEO_BITRATE_KBPS = 500

# Cryptography parameters
ED25519_PRIVATE_KEY_SIZE = 32
ED25519_PUBLIC_KEY_SIZE = 32
ED25519_SIGNATURE_SIZE = 64
P256_PRIVATE_KEY_SIZE = 32
P256_PUBLIC_KEY_UNCOMPRESSED_SIZE = 65
AES_KEY_SIZE = 32
HKDF_SALT = b"AetherSignal"
