// SPDX-License-Identifier: MIT

package aethernet.dtn

import aethernet.models.DtnBundle
import aethernet.models.DtnDeliveryReceipt
import org.json.JSONArray
import org.json.JSONObject
import org.junit.jupiter.api.Test
import java.io.File
import java.time.Instant
import java.util.UUID
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals

/**
 * Cross-language DTN-envelope parity: the Kotlin port must reproduce the Go
 * oracle's byte vectors (fixtures/dtn/expected/<name>.bin, generated by
 * go/cmd/dtnfixturegen) byte-for-byte for every case in fixtures/dtn/inputs.json,
 * and deserialize each back to matching fields. Any drift between Kotlin and the
 * other seven ports surfaces here as a byte mismatch.
 *
 * Kotlin's DtnBundle carries `status` as a String label, so this test maps the
 * fixture's u8 status ordinal to/from that label (the same mapping DtnEnvelope
 * applies on the wire).
 */
class DtnEnvelopeFixtureTest {

    private fun repoRoot(): File {
        var dir: File? = File(".").canonicalFile
        repeat(10) {
            val candidate = File(dir, "AetherNetProtocol.slnx")
            if (candidate.exists()) return dir!!
            dir = dir?.parentFile ?: return@repeat
        }
        throw IllegalStateException("AetherNetProtocol.slnx not found from ${File(".").canonicalFile}")
    }

    private fun inputs(): JSONArray =
        JSONArray(File(repoRoot(), "fixtures/dtn/inputs.json").readText())

    private fun expected(name: String): ByteArray =
        File(repoRoot(), "fixtures/dtn/expected/$name.bin").readBytes()

    private fun unhex(s: String): ByteArray {
        if (s.isEmpty()) return ByteArray(0)
        return ByteArray(s.length / 2) { i ->
            ((Character.digit(s[i * 2], 16) shl 4) + Character.digit(s[i * 2 + 1], 16)).toByte()
        }
    }

    private fun payloadFor(o: JSONObject): ByteArray {
        val len = o.optInt("encrypted_payload_len", 0)
        if (len > 0) return ByteArray(len) { (it % 256).toByte() }
        return unhex(o.optString("encrypted_payload_hex", ""))
    }

    private fun statusLabel(v: Int): String = when (v) {
        0 -> "Pending"
        1 -> "InCustody"
        2 -> "Delivered"
        3 -> "Expired"
        4 -> "Failed"
        else -> "Pending"
    }

    private fun statusInt(label: String): Int = when (label) {
        "Pending" -> 0
        "InCustody" -> 1
        "Delivered" -> 2
        "Expired" -> 3
        "Failed" -> 4
        else -> 0
    }

    private fun nullableStr(o: JSONObject, key: String): String? =
        if (o.isNull(key)) null else o.optString(key, "")

    private fun bundleFromInput(o: JSONObject): DtnBundle = DtnBundle(
        id = UUID.fromString(o.getString("id")),
        senderUhid = o.optString("sender_uhid", ""),
        recipientUhid = o.optString("recipient_uhid", ""),
        encryptedPayload = payloadFor(o),
        priority = o.optInt("priority", 0),
        status = statusLabel(o.optInt("status", 0)),
        copyCount = o.optInt("copy_count", 0),
        maxCopies = o.optInt("max_copies", 0),
        senderGeohash = nullableStr(o, "sender_geohash"),
        recipientLastGeohash = nullableStr(o, "recipient_last_geohash"),
        hopCount = o.optInt("hop_count", 0),
        createdAt = Instant.ofEpochMilli(o.getLong("created_at_ms")),
        expiresAt = Instant.ofEpochMilli(o.getLong("expires_at_ms"))
    )

    private fun serializeCase(o: JSONObject): ByteArray = when (val kind = o.getString("kind")) {
        "bundle" -> DtnEnvelope.serializeBundle(bundleFromInput(o))
        "custody_ack" -> DtnEnvelope.serializeCustodyAck(
            UUID.fromString(o.getString("bundle_id")),
            o.optBoolean("accepted", false)
        )
        "delivery_receipt" -> DtnEnvelope.serializeDeliveryReceipt(
            DtnDeliveryReceipt(
                bundleId = UUID.fromString(o.getString("bundle_id")),
                recipientUhid = o.optString("recipient_uhid", ""),
                totalHops = o.optInt("total_hops", 0),
                totalCustodyTransfers = o.optInt("total_custody_transfers", 0),
                deliveredAt = Instant.ofEpochMilli(o.getLong("delivered_at_ms"))
            )
        )
        else -> throw IllegalArgumentException("unknown kind $kind")
    }

    /** Every input case serialises byte-for-byte to its Go-oracle .bin vector. */
    @Test
    fun `dtn envelope serialises byte-identical to the Go oracle`() {
        val arr = inputs()
        for (i in 0 until arr.length()) {
            val o = arr.getJSONObject(i)
            val name = o.getString("name")
            assertContentEquals(expected(name), serializeCase(o), "$name: serialize byte mismatch")
        }
    }

    /** Every .bin vector deserialises back to the input fields (incl. status label + geohash). */
    @Test
    fun `dtn envelope deserialises every field round-trip`() {
        val arr = inputs()
        for (i in 0 until arr.length()) {
            val o = arr.getJSONObject(i)
            val name = o.getString("name")
            val data = expected(name)
            when (o.getString("kind")) {
                "bundle" -> {
                    val b = DtnEnvelope.deserializeBundle(data)
                    assertEquals(UUID.fromString(o.getString("id")), b.id, "$name id")
                    assertEquals(o.optInt("priority", 0), b.priority, "$name priority")
                    assertEquals(o.optInt("status", 0), statusInt(b.status), "$name status")
                    assertEquals(o.optInt("copy_count", 0), b.copyCount, "$name copy_count")
                    assertEquals(o.optInt("max_copies", 0), b.maxCopies, "$name max_copies")
                    assertEquals(o.optInt("hop_count", 0), b.hopCount, "$name hop_count")
                    assertEquals(o.getLong("created_at_ms"), b.createdAt.toEpochMilli(), "$name created_at")
                    assertEquals(o.getLong("expires_at_ms"), b.expiresAt.toEpochMilli(), "$name expires_at")
                    assertEquals(o.optString("sender_uhid", ""), b.senderUhid, "$name sender_uhid")
                    assertEquals(o.optString("recipient_uhid", ""), b.recipientUhid, "$name recipient_uhid")
                    assertEquals(nullableStr(o, "sender_geohash") ?: "", b.senderGeohash ?: "", "$name sender_geohash")
                    assertEquals(
                        nullableStr(o, "recipient_last_geohash") ?: "",
                        b.recipientLastGeohash ?: "",
                        "$name recipient_last_geohash"
                    )
                    assertContentEquals(payloadFor(o), b.encryptedPayload, "$name payload")
                }
                "custody_ack" -> {
                    val (id, accepted) = DtnEnvelope.deserializeCustodyAck(data)
                    assertEquals(UUID.fromString(o.getString("bundle_id")), id, "$name bundle_id")
                    assertEquals(o.optBoolean("accepted", false), accepted, "$name accepted")
                }
                "delivery_receipt" -> {
                    val r = DtnEnvelope.deserializeDeliveryReceipt(data)
                    assertEquals(UUID.fromString(o.getString("bundle_id")), r.bundleId, "$name bundle_id")
                    assertEquals(o.optString("recipient_uhid", ""), r.recipientUhid, "$name recipient_uhid")
                    assertEquals(o.optInt("total_hops", 0), r.totalHops, "$name total_hops")
                    assertEquals(
                        o.optInt("total_custody_transfers", 0),
                        r.totalCustodyTransfers,
                        "$name total_custody_transfers"
                    )
                    assertEquals(o.getLong("delivered_at_ms"), r.deliveredAt.toEpochMilli(), "$name delivered_at")
                }
            }
        }
    }
}
