// SPDX-License-Identifier: MIT

//! BIP-39 recovery-phrase backup for an AetherNet identity.
//!
//! An AetherNet identity is an Ed25519 key pair whose private key is a 32-byte
//! seed — exactly 256 bits, which map cleanly onto a standard 24-word BIP-39
//! phrase. The user writes down 24 ordinary words; from those words alone the
//! identity is fully reconstructed on any device. No server, no account, no
//! custodian — the phrase *is* the identity.
//!
//! This is the real, standard BIP-39 algorithm, verified against the official
//! Trezor test vectors (`fixtures/bip39/vectors.json`). A phrase produced here
//! restores on any conformant BIP-39 wallet, and every AetherNet language SDK
//! reproduces the same words and seed byte-for-byte.
//!
//! ```text
//!   entropy (16..32 bytes, multiple of 4)  --entropy_to_mnemonic-->  phrase
//!   phrase  --mnemonic_to_entropy-->  entropy      (SHA-256 checksum enforced)
//!   phrase  --mnemonic_to_seed-->  64-byte seed    (PBKDF2-HMAC-SHA512, 2048 rounds)
//! ```
//!
//! This mirrors the C# reference `AetherNet.Security.Backup.Bip39Mnemonic` /
//! `IdentityBackup` byte-for-byte.

use ed25519_dalek::SigningKey;
use sha2::{Digest, Sha256, Sha512};

const PBKDF_ITERATIONS: u32 = 2048;
const SEED_LENGTH_BYTES: usize = 64;

/// The official BIP-39 English wordlist (2048 words), embedded verbatim from
/// `fixtures/bip39/english.txt` at compile time.
///
/// Source: <https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt>
/// SHA-256: `2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda`
///
/// Embedding via `include_str!` guarantees the byte-exact list — the same block
/// verified against that SHA-256 in the fixture test. Every AetherNet language
/// SDK embeds this identical list, so a phrase generated by one restores on any
/// other, and on any standard BIP-39 wallet tool.
const WORDLIST_RAW: &str = include_str!("../../../fixtures/bip39/english.txt");

/// Errors from BIP-39 codec / identity-backup operations.
///
/// Mirrors the error style of [`crate::security::ed25519`] — a small enum with
/// `Display` (via [`std::fmt`]) and [`std::error::Error`], returned in a
/// [`Result`] so a mistyped word errors rather than silently reconstructing a
/// different secret.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Bip39Error {
    /// Entropy length was not 16, 20, 24, 28, or 32 bytes.
    InvalidEntropyLength(usize),
    /// Word count was not 12, 15, 18, 21, or 24.
    InvalidWordCount(usize),
    /// A word in the phrase is not in the BIP-39 English wordlist.
    UnknownWord(String),
    /// The SHA-256 checksum embedded in the phrase did not match the entropy.
    InvalidChecksum,
    /// An AetherNet identity seed / private key must be exactly 32 bytes.
    NotIdentitySeed(usize),
}

impl std::fmt::Display for Bip39Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Bip39Error::InvalidEntropyLength(n) => write!(
                f,
                "entropy must be 16, 20, 24, 28, or 32 bytes (got {n})"
            ),
            Bip39Error::InvalidWordCount(n) => write!(
                f,
                "mnemonic must be 12, 15, 18, 21, or 24 words (got {n})"
            ),
            Bip39Error::UnknownWord(w) => write!(f, "unknown mnemonic word: '{w}'"),
            Bip39Error::InvalidChecksum => write!(f, "mnemonic checksum is invalid"),
            Bip39Error::NotIdentitySeed(n) => write!(
                f,
                "an AetherNet identity seed must be 32 bytes (a 256-bit / 24-word phrase) (got {n})"
            ),
        }
    }
}

impl std::error::Error for Bip39Error {}

/// Lazily-built word list, split from the embedded raw block on ASCII
/// whitespace. Kept as `Vec<&'static str>` so index -> word is O(1).
fn wordlist() -> &'static Vec<&'static str> {
    use std::sync::OnceLock;
    static WORDS: OnceLock<Vec<&'static str>> = OnceLock::new();
    WORDS.get_or_init(|| WORDLIST_RAW.split_whitespace().collect())
}

/// word -> index lookup, built once from the embedded wordlist.
fn word_index() -> &'static std::collections::HashMap<&'static str, usize> {
    use std::sync::OnceLock;
    static INDEX: OnceLock<std::collections::HashMap<&'static str, usize>> = OnceLock::new();
    INDEX.get_or_init(|| {
        wordlist()
            .iter()
            .enumerate()
            .map(|(i, &w)| (w, i))
            .collect()
    })
}

/// Splits a mnemonic into words on ASCII whitespace, dropping empty entries —
/// the equivalent of C#'s `string.Split(null, RemoveEmptyEntries)`.
fn split_words(mnemonic: &str) -> Vec<&str> {
    mnemonic.split_whitespace().collect()
}

/// Encodes entropy as a BIP-39 mnemonic phrase (single-space-separated words).
///
/// `entropy` must be 16, 20, 24, 28, or 32 bytes (128..256 bits, a multiple of
/// 4 bytes). The checksum is the top `entropy_bits / 32` bits of
/// `SHA-256(entropy)[0]`; the concatenated `entropy || checksum` bit stream is
/// read big-endian in 11-bit groups into word indices.
pub fn entropy_to_mnemonic(entropy: &[u8]) -> Result<String, Bip39Error> {
    let len = entropy.len();
    if len < 16 || len > 32 || len % 4 != 0 {
        return Err(Bip39Error::InvalidEntropyLength(len));
    }

    let ent_bits = len * 8;
    let cs_bits = ent_bits / 32; // 4..8 checksum bits
    let checksum = Sha256::digest(entropy)[0]; // only the top cs_bits are used

    let word_count = (ent_bits + cs_bits) / 11;
    let words = wordlist();
    let mut out = String::new();

    for w in 0..word_count {
        let mut index = 0usize;
        for b in 0..11 {
            let bit_pos = w * 11 + b;
            let bit = if bit_pos < ent_bits {
                (entropy[bit_pos >> 3] >> (7 - (bit_pos & 7))) & 1
            } else {
                (checksum >> (7 - (bit_pos - ent_bits))) & 1
            };
            index = (index << 1) | (bit as usize);
        }
        if w > 0 {
            out.push(' ');
        }
        out.push_str(words[index]);
    }

    Ok(out)
}

/// Decodes a BIP-39 mnemonic back to its entropy, enforcing the SHA-256
/// checksum.
///
/// Returns [`Bip39Error::UnknownWord`] on an unknown word,
/// [`Bip39Error::InvalidWordCount`] on a wrong word count, or
/// [`Bip39Error::InvalidChecksum`] on a checksum mismatch — so a mistyped
/// phrase is rejected rather than silently yielding the wrong secret.
pub fn mnemonic_to_entropy(mnemonic: &str) -> Result<Vec<u8>, Bip39Error> {
    let words = split_words(mnemonic);
    if !matches!(words.len(), 12 | 15 | 18 | 21 | 24) {
        return Err(Bip39Error::InvalidWordCount(words.len()));
    }

    let total_bits = words.len() * 11;
    let cs_bits = total_bits / 33;
    let ent_bits = total_bits - cs_bits;
    let mut entropy = vec![0u8; ent_bits / 8];
    let mut actual_checksum: u32 = 0;

    let index_map = word_index();
    for (w, &word) in words.iter().enumerate() {
        let &index = index_map
            .get(word)
            .ok_or_else(|| Bip39Error::UnknownWord(word.to_string()))?;

        for b in 0..11 {
            let bit = ((index >> (10 - b)) & 1) as u8;
            let bit_pos = w * 11 + b;
            if bit_pos < ent_bits {
                entropy[bit_pos >> 3] |= bit << (7 - (bit_pos & 7));
            } else {
                actual_checksum = (actual_checksum << 1) | (bit as u32);
            }
        }
    }

    let expected_checksum = (Sha256::digest(&entropy)[0] >> (8 - cs_bits)) as u32;
    if actual_checksum != expected_checksum {
        return Err(Bip39Error::InvalidChecksum);
    }

    Ok(entropy)
}

/// Derives the 64-byte BIP-39 seed from a mnemonic and optional passphrase,
/// using PBKDF2-HMAC-SHA512 with 2048 iterations and salt `"mnemonic" + passphrase`.
///
/// The password is the single-space-joined phrase as UTF-8. Per the BIP-39
/// spec both inputs are NFKD-normalized; the official English wordlist and the
/// `"mnemonic"` salt prefix are all NFKD-invariant ASCII, so for ASCII inputs
/// this is exact. Full NFKD of a non-ASCII passphrase is out of scope — there
/// is no unicode-normalization crate in this crate's dependencies, matching the
/// note in the C SDK. (For the test vectors the passphrase is `"TREZOR"`, ASCII.)
pub fn mnemonic_to_seed(mnemonic: &str, passphrase: &str) -> Vec<u8> {
    let normalized_mnemonic = split_words(mnemonic).join(" ");
    let salt = format!("mnemonic{passphrase}");

    let mut out = vec![0u8; SEED_LENGTH_BYTES];
    pbkdf2::pbkdf2_hmac::<Sha512>(
        normalized_mnemonic.as_bytes(),
        salt.as_bytes(),
        PBKDF_ITERATIONS,
        &mut out,
    );
    out
}

/// Returns `true` if `mnemonic` is a well-formed BIP-39 phrase with a valid
/// checksum.
pub fn is_valid(mnemonic: &str) -> bool {
    mnemonic_to_entropy(mnemonic).is_ok()
}

/// Recovery-phrase backup and restore for an AetherNet identity.
///
/// Mirrors the C# `AetherNet.Security.Backup.IdentityBackup`.
pub struct IdentityBackup;

impl IdentityBackup {
    /// Produces the 24-word recovery phrase for an identity's 32-byte Ed25519
    /// private seed.
    ///
    /// Returns [`Bip39Error::NotIdentitySeed`] if the seed is not 32 bytes.
    pub fn to_recovery_phrase(ed25519_private_key: &[u8]) -> Result<String, Bip39Error> {
        if ed25519_private_key.len() != 32 {
            return Err(Bip39Error::NotIdentitySeed(ed25519_private_key.len()));
        }
        entropy_to_mnemonic(ed25519_private_key)
    }

    /// Restores a full identity key pair from a 24-word recovery phrase. The
    /// BIP-39 checksum is enforced, so a mistyped word is rejected rather than
    /// silently reconstructing a different identity.
    ///
    /// Returns `(public_key: 32 bytes, private_key: 32-byte seed)`, mirroring
    /// the `(private, public)` tuple convention of
    /// [`crate::security::ed25519::Ed25519SigningService`] (public first here to
    /// match C#'s `KeyPair(publicKey, privateKey)`).
    pub fn from_recovery_phrase(recovery_phrase: &str) -> Result<(Vec<u8>, Vec<u8>), Bip39Error> {
        let private_key = mnemonic_to_entropy(recovery_phrase)?;
        if private_key.len() != 32 {
            return Err(Bip39Error::NotIdentitySeed(private_key.len()));
        }

        let seed: [u8; 32] = private_key
            .as_slice()
            .try_into()
            .map_err(|_| Bip39Error::NotIdentitySeed(private_key.len()))?;
        let public_key = SigningKey::from_bytes(&seed).verifying_key().to_bytes();

        Ok((public_key.to_vec(), private_key))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wordlist_has_2048_words() {
        assert_eq!(wordlist().len(), 2048);
        assert_eq!(wordlist()[0], "abandon");
        assert_eq!(wordlist()[2047], "zoo");
    }

    #[test]
    fn embedded_wordlist_sha256_matches() {
        // Re-verify the embedded block is the exact official list. The canonical
        // form is one word per line terminated by '\n' (2048 lines, trailing
        // newline) — reconstruct that from the split words and hash it.
        let mut canonical = String::new();
        for w in wordlist() {
            canonical.push_str(w);
            canonical.push('\n');
        }
        let digest = Sha256::digest(canonical.as_bytes());
        let hex: String = digest.iter().map(|b| format!("{:02x}", b)).collect();
        assert_eq!(
            hex,
            "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda"
        );
    }

    #[test]
    fn all_zero_entropy_round_trips() {
        let entropy = [0u8; 16];
        let phrase = entropy_to_mnemonic(&entropy).unwrap();
        assert_eq!(
            phrase,
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        );
        assert_eq!(mnemonic_to_entropy(&phrase).unwrap(), entropy);
    }

    #[test]
    fn rejects_bad_entropy_length() {
        assert_eq!(
            entropy_to_mnemonic(&[0u8; 17]),
            Err(Bip39Error::InvalidEntropyLength(17))
        );
        assert_eq!(
            entropy_to_mnemonic(&[0u8; 15]),
            Err(Bip39Error::InvalidEntropyLength(15))
        );
    }

    #[test]
    fn rejects_bad_word_count() {
        assert_eq!(
            mnemonic_to_entropy("abandon abandon abandon"),
            Err(Bip39Error::InvalidWordCount(3))
        );
    }

    #[test]
    fn is_valid_matches() {
        assert!(is_valid(
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        ));
        assert!(!is_valid(
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon"
        ));
    }
}
